bb.I2CInit()
bb.setBrightness(100)
basic.forever(function () {
    serial.writeLine("Turn on the left light, motor forward, RGB light red")
    bb.setIndexColor(bb.ledRange(1, 4), bb.NeoPixelColors.Red)
    bb.controlLED(bb.bbled.LeftLed, bb.bbswitch.Open)
    basic.pause(2000)
    serial.writeLine("Turn on the right side light, motor back, RGB light yellow")
    bb.setIndexColor(bb.ledRange(1, 4), bb.NeoPixelColors.Yellow)
    bb.controlLED(bb.bbled.LeftLed, bb.bbswitch.Close)
    bb.controlLED(bb.bbled.RightLed, bb.bbswitch.Open)
    basic.pause(2000)
    serial.writeLine("Turn on the side lights, motor forward, RGB light green")
    bb.controlLED(bb.bbled.AllLed, bb.bbswitch.Open)
    bb.setIndexColor(bb.ledRange(1, 4), bb.NeoPixelColors.Green)
    basic.pause(2000)
    serial.writeLine("Printing sensor data")
    serial.writeLine("SensorL1 status:" + bb.readLineSensorState(bb.bblinesensor.SensorL1))
    serial.writeLine("SensorL1 ADC:" + bb.readLineSensorData(bb.bblinesensor.SensorL1))
})
